### ISSUE TITLE
no feedback when a push fails

### ISSUE THREAD

**Issue by Pomax** [ddollar/heroku-config#29]
Pushing an .env of the format
```
export VAR_1="..."
export VAR_2="..."
export VAR_3="..."
...
```
using `$> heroku config:push` and then checking the resulting config shows zero change, without the command having said anything at all. No errors, no warnings, no notices.

**Comment by sedge** [comment]
:+1: 

This is a dealbreaker for me, since the tool is essentially broken.

**Comment by sedge** [comment]
It seems we aren't the only ones encountering this: http://stackoverflow.com/questions/27899517/heroku-configpush-not-adding-environment-variables

**Comment by ddollar** [comment]
I no longer use Heroku day to day so I am no longer going to be maintaining this plugin. If you'd like to submit a pull request that solves the issue I would be happy to take a look and merge..

**Comment by Pomax** [comment]
does heroku know? (they kind of expressly link to this repo in their dev docs =x)

**Comment by jmccartie** [comment]
@Pomax I just installed the plugin and pushed/pulled some dummy configs just fine.  Any guesses as to what's failing to I can try to reproduce?

**Comment by jmccartie** [comment]
Actually, it looks like my PR fixes the issue in the SO post (spaces between "="'s), but not this one. I've never seen a `.env` file with `export` in front -- I've usually only seen that format with Pow.

I guess we could tweak the regex even further...?

**Comment by jmccartie** [comment]
The issue here is the `export` -- this is not a valid format for Foreman or Heroku.  I've added an error (and exit) if the format is incorrect.  This will warn on *this* issue, as well as the one in the SO post (spaces around `=`'s)

**Comment by Pomax** [comment]
:+1:

**Comment by jmccartie** [comment]
@Pomax Agreed.  That's the route I took at first ... however, it then creates other problems for `config:pull` since it will then need to know what format to write your vars in.  Much easier to stick to the correct format than make this plugin overly complicated.

**Comment by Pomax** [comment]
`--with-export` for a leading `export `? Stripping spacing shouldn't matter all that much, since they're completely irrelevant for env parsing purposes.

**Comment by ddollar** [comment]
The `.env` file that heroku-config knows how to work with does not contain `export` statements. I don't want to cruft it up with a ton of options if possible.

The code for these plugins are fairly simple and since you can install them easily from a git url I think it makes more sense for you to fork it to add the `export` handling.

**Comment by Pomax** [comment]
to be fair: if you don't really maintain this package anymore, I'm not sure I see the benefit of creating a fork over simply landing @jmccartie's PR so that the rest of the world gets a better heroku-config for free instead of having to find a fork that's likely not going to show up on google or npmjs

**Comment by ddollar** [comment]
Because the changes are not as straightforward as they seem. Perhaps someone has comments in their `.env` which would start throwing errors with this pull request.

**Comment by Pomax** [comment]
good point.

**Comment by sedge** [comment]
One way or another, with parsing options or without them, shouldn't this fix be landed? At the moment the tool is broken because it gives *no feedback on failure* or even an indication that failure occurred. Throwing errors on comments is at least more honest about the formatting expectations, makes the tool usable and might compel people to fork it as you suggest if they want to improve the behaviour.

I don't know ruby so I'm not positioned to help out with the coding, but if there's anything else I can do to help push this through let me know.

**Comment by ddollar** [comment]
I have proposed an alternate change over on the pull request to allow for checking for valid contents in an `.env` file. Given that this plugin has not seen significant changes in almost 2.5 years I'm going to err on the conservative side here.

**Comment by jmccartie** [comment]
PR updated
